spring:
  application:
    name: Section1
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:eazybank}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:yuosef}
  jpa:
    show-sql: ${JPA_SHOWSQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMATSQL:true}
  config:
    import: application_prod.yml
  profiles:
    active: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs}


#  security:
#    oauth2:
#      resourceserver:
#        opaque:
#          introspection-uri": ${INTROSPECT_URI:http://localhost:8180/realms/eazybankdev/protocol/openid-connect/token/introspect}
#          introspection-client-id: ${INTROSPECT_ID:eazybankintrospect}
#          introspection-client-secret: ${INTROSPECT_SECRET:w1IvV88jPp3WEKumOTibszrJzpIWx4Ql}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}

